### ISSUE TITLE
New course page shows incorrect schema extensions

### ISSUE THREAD

**Issue by taylortom** [adapt-security/adapt-authoring-content#16]
### What happened?

The course edit page displays incorrect schema extensions when creating a new course.

### Steps to reproduce

1. Go into course settings of an existing course with at least one extension enabled
2. Go back to dashboard and create a new course
3. Notice the same extension settings are visible from the course in step 1.

### Authoring tool version

v1

**Comment by chris-steele** [comment]
Confirmed +1
