### ISSUE TITLE
createrecursive endpoint now returns all new items rather than root

### ISSUE THREAD

**Issue by taylortom** [adapt-security/adapt-authoring-content#19]
Initially, the endpoint returned the top-level/root item of the created items. We now get an array of all new items. 

How should this work?

**Comment by chris-steele** [comment]
I introduced this change with #17. Apologies if this is causing problesm. The first item in the returned list will be the root item, so there is consistency at least.

**Comment by taylortom** [comment]
Agreed the new return data is preferable, so nothing to do here
