### ISSUE TITLE
_sortOrder incorrect on course copy

### ISSUE THREAD

**Issue by taylortom** [adapt-security/adapt-authoring-content#9]
### What happened?

Content items appear out of order (this likely affects all content copy, not just course).

### Expected behaviour

Content objects should retain _sortOrder from original content.

### Steps to reproduce

Copy a course with multiple pages. Observe the incorrect order in the menu structure page.

### Authoring tool version

v1

**Comment by chris-steele** [comment]
I'm unable to replicate this. I've tried:

- creating a course with 3/4 pages
- making a copy (order was preserved)
- re-ordering the pages in the original course and then making a copy (order was preserved)
- making a copy of the above copies (order was preserved)

Let me know if there is a specific path to replicating this issue and I'll take another look.
